version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - charity-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - charity-net

  mongo:
    image: mongo:5.0
    container_name: charity-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - charity-net

networks:
  charity-net:

volumes:
  mongo-data: